cloud:
  aws:
    credentials:
      access-key: AKIA2UC3FB57HLV3EEAI
      secret-key: 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
    region:
      static: eu-north-1
    stack:
      auto: false



application:
  bucket:
    name: bucketibfinki



server:
  port: 9090