cloud:
  aws:
    credentials:
      access-key: AKIA2UC3FB57JCQOUUFW
      secret-key: 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
    region:
      static: eu-north-1
    stack:
      auto: false



application:
  bucket:
    name: bucketibfinki



server:
  port: 9090